### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by j-bac** [saezlab/kasumi_bench#1]
Would you have data available for reproducibility ? For example I downloaded data from [https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8792442/](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8792442/) but inside `Image Data/Segmetation_Outlines_and_Labels_Mendeley/` are .tiff files rather than the .csv loaded in your scripts

**Comment by jtanevski** [comment]
Thanks for your patience, I seem to have missed this issue. We are now updating the manuscript and the benchmark, but the data remains the same. To address your question, there is a simple way to extract the information needed for running Kasumi on the DCIS dataset. All information is contained in the _labels.tiff files and the segmentation mask within. Here is a Python code:

```
import glob
import re
from skimage import io
from skimage.measure import regionprops_table
import pandas

for f in glob.glob("*_labels.tiff"):
    mask = io.imread(f)
    rp = regionprops_table(mask,  properties=('label', 'centroid'))
    pandas.DataFrame(rp).to_csv(re.findall("\d+", f)[0] + ".csv", index = False)
```

**Comment by jtanevski** [comment]
I also added the instructions in the README file.
